# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY client/package*.json ./
COPY client/.env ./
RUN npm install -f
COPY client/ .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80